//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ditat.Data.EntityModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class CategoryProperty
    {
        public int Id { get; set; }
        public Nullable<int> CategoryId { get; set; }
        public string Name { get; set; }
        public int SortValue { get; set; }
        public Nullable<int> Creator { get; set; }
        public string ValueType { get; set; }
    
        public virtual Category Category { get; set; }
    }
}
