//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ditat.Data.EntityModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class LanguageText
    {
        public int Id { get; set; }
        public int LanguageId { get; set; }
        public string KeyName { get; set; }
        public string Value { get; set; }
    }
}
