//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ditat.Data.EntityModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Product()
        {
            this.ProductImages = new HashSet<ProductImage>();
        }
    
        public System.Guid Id { get; set; }
        public string Name { get; set; }
        public string Barcode { get; set; }
        public string Price { get; set; }
        public string Category { get; set; }
        public string Properties { get; set; }
        public Nullable<System.DateTime> Inserted { get; set; }
        public Nullable<int> CategoryId { get; set; }
        public string Comment { get; set; }
        public Nullable<int> ProductStatusId { get; set; }
        public Nullable<int> ProductConditionId { get; set; }
        public int ProductNumber { get; set; }
        public bool Shipping { get; set; }
        public string ShopUrl { get; set; }
        public Nullable<int> ShippingCost { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductImage> ProductImages { get; set; }
        public virtual Category Category1 { get; set; }
        public virtual ProductCondition ProductCondition { get; set; }
        public virtual ProductStatu ProductStatu { get; set; }
    }
}
